---

# this file is used to run ansible inside vagrant itself with a local connection.
- hosts: localhost
  connection: local
  sudo: True
  roles:
    - { role: ansible-rabbitmq,          tags: ["rabbitmq"] }