# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.provision :shell do |shell|
    shell.inline = "apt-get update && apt-get -y install python-software-properties && add-apt-repository ppa:rquillo/ansible && apt-get update && apt-get -y install ansible && cd /vagrant && ansible-playbook rabbit_vagrant.yml"
  end
  config.vm.network :forwarded_port, guest: 5672, host: 5672
  config.vm.network :forwarded_port, guest: 15672, host: 15672
end
