---

#
# The rabbitmq server must be completely stopped before changing the erlang cookie.
# otherwise the server screws up and is unable to stop or start again when you kill the process
#

- name: check current erlang cookie
  shell: "cat {{ rabbitmq_erlang_cookie_path }}"
  changed_when: False
  register: rabbitmq_erlang_cookie_current

- name: "stop rabbitmq-server before updating erlang cookie"
  service: name=rabbitmq-server state=stopped
  when: rabbitmq_erlang_cookie != rabbitmq_erlang_cookie_current.stdout

- name: "update rabbitmq erlang cookie and backup the old one"
  template:
    src="erlang_cookie.j2"
    dest="{{ rabbitmq_erlang_cookie_path }}"
    owner="rabbitmq"
    group="rabbitmq"
    mode="0400"
    backup=yes
  when: rabbitmq_erlang_cookie != rabbitmq_erlang_cookie_current.stdout

- name: "start rabbitmq-server again"
  service: name=rabbitmq-server state=started
  when: rabbitmq_erlang_cookie != rabbitmq_erlang_cookie_current.stdout