---

- include: install/main.yml
- include: configuration.yml
- include: plugins.yml
- include: vhost.yml
- include: policies.yml
- include: federation.yml
  when: rabbitmq_federation

- include: erlang_cookie.yml
  when: rabbitmq_clustering
  tags: ["rabbitmq-erlang"]

- include: cluster.yml
  when: rabbitmq_clustering
  tags: ["rabbitmq-cluster"]
